const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const Module = require("node:module");

// PR B, B5: the processor list says what Anthropic receives. This captures the
// actual outgoing request rather than reading the prompt builder and hoping,
// and writes the captured field list to docs/ai-request-fields.json so the
// document can be checked against something.
//
// The captured request is what a merchant would be told: the play, the
// audience's DESCRIPTION, the brand's own words, and the catalogue. No
// customer identifies anyone in it.

const OUT = path.join(__dirname, "..", "..", "docs", "ai-request-fields.json");

// The SDK is required lazily inside the service, so a stub in the module cache
// is what the service will pick up.
function stubAnthropic(capture) {
  const load = Module._load;
  Module._load = function (request, parent, isMain) {
    if (request === "@anthropic-ai/sdk") {
      return class {
        constructor() {
          this.messages = {
            create: async (payload) => {
              capture.push(payload);
              return {
                content: [{
                  text: JSON.stringify({
                    subject: "Your size is back",
                    previewText: "Only a few left",
                    headline: "Back in stock",
                    body: "The piece you looked at is available again.",
                    support: "Free returns.",
                    cta: "Shop now",
                    featured_product_id: null,
                  }),
                }],
              };
            },
          };
        }
      };
    }
    return load.apply(this, arguments);
  };
  return () => { Module._load = load; };
}

test("the copy request carries the play and the catalogue, and identifies no customer", async () => {
  const captured = [];
  const restore = stubAnthropic(captured);
  const savedKey = process.env.ANTHROPIC_API_KEY;
  process.env.ANTHROPIC_API_KEY = "test-key-not-used";
  // Required after the env var is set: the service reads it at call time, but
  // the module must not have cached a client from an earlier test.
  delete require.cache[require.resolve("../src/services/copywriterService")];
  const { generateCampaignCopy } = require("../src/services/copywriterService");

  try {
    const result = await generateCampaignCopy({
      play: {
        play_id: "cohort_journey_first_to_second",
        play_name: "First to second purchase",
        mechanism: "Customers who bought once and have not returned",
        play_one_liner: "bought once, 30-90 days ago",
      },
      brandContext: {
        brandName: "Fern & Foss",
        category: "skincare",
        messaging: { useWords: ["botanical", "unscented"] },
      },
      template: { name: "Simple", subject: "Hello", cta: "Shop" },
      products: [{ id: "p1", title: "Cleansing Balm", productType: "cleanser" }],
    });
    assert.equal(result.available, true);
    assert.equal(captured.length, 1, "exactly one model call");
  } finally {
    restore();
    if (savedKey === undefined) delete process.env.ANTHROPIC_API_KEY;
    else process.env.ANTHROPIC_API_KEY = savedKey;
    delete require.cache[require.resolve("../src/services/copywriterService")];
  }

  const request = captured[0];
  const body = JSON.stringify(request);

  // What a processor disclosure has to be able to promise.
  for (const forbidden of [
    "@example.com", "@gmail", "customer_id", "cust-", "recipient",
    "first_name", "last_name", "phone", "address",
  ]) {
    assert.ok(!body.includes(forbidden), `the request carries "${forbidden}"`);
  }

  // What it does carry, named so a change to the prompt shows up here.
  assert.ok(body.includes("Fern & Foss"), "the brand's own name");
  assert.ok(body.includes("Cleansing Balm"), "the catalogue");
  assert.ok(body.includes("bought once, 30-90 days ago"), "the audience's description, not its members");

  fs.writeFileSync(
    OUT,
    JSON.stringify({
      capturedBy: "api/tests/aiPayload.test.js",
      note: "Fields sent to Anthropic when generating campaign copy. Regenerated by the test suite.",
      topLevelFields: Object.keys(request).sort(),
      model: request.model,
      userMessageFields: [
        "mechanism", "audience description", "brand name and category",
        "store words to favour", "template name", "product id / title / type",
        "merchant-locked slots (when present)", "merchant revision note (when present)",
      ],
      carriesCustomerIdentifiers: false,
    }, null, 2) + "\n"
  );
});
