const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const {
  buildEngineInputSnapshot,
  fetchedOrderCoverage,
  observedCoverage,
  snapshotToCsv,
} = require("../src/services/engineInputSnapshot");

const FIXTURE_DIR = path.join(__dirname, "fixtures");
const input = JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, "engineInput.sample.json"), "utf8"));

test("the refactor produces byte-identical normalized input", () => {
  // engineInput.sample.golden.csv was generated by the PRE-refactor
  // writeOrdersCsv (git HEAD before this branch), so this is an equivalence
  // check against the old implementation, not a snapshot of the new one.
  // It covers quoted cells, an embedded newline, the synthetic line item for an
  // order with none, processed_at winning over created_at, and null handling.
  const golden = fs.readFileSync(path.join(FIXTURE_DIR, "engineInput.sample.golden.csv"), "utf8");
  assert.equal(snapshotToCsv(buildEngineInputSnapshot(input)), golden);
});

test("the snapshot counts rows, not orders", () => {
  const snapshot = buildEngineInputSnapshot(input);
  assert.equal(snapshot.orderCount, 3);
  assert.equal(snapshot.rowCount, 4, "order 1001 has two line items");
  assert.equal(snapshot.shop.shop_domain, "fixture-shop.myshopify.com");
});

test("coverage spans the order dates the engine will actually see", () => {
  const { coverage } = buildEngineInputSnapshot(input);
  assert.equal(coverage.known, true);
  // Anchored on processed_at (Jan 4 → Jun 1), NOT the identical created_at
  // stamps every one of these rows carries from being API-imported.
  assert.equal(coverage.earliestOrderAt, "2026-01-04T09:30:00.000Z");
  assert.equal(coverage.latestOrderAt, "2026-06-01T12:00:00.000Z");
  assert.equal(coverage.daysCovered, 149);
});

test("undated orders yield unknown coverage, never zero days", () => {
  const coverage = observedCoverage([{ "Created at": "" }, { "Created at": "not a date" }]);
  assert.equal(coverage.known, false);
  assert.equal(coverage.daysCovered, null);
  assert.equal(coverage.earliestOrderAt, null);
});

test("a single day of orders covers one day, not zero", () => {
  const coverage = observedCoverage([
    { "Created at": "2026-03-01T01:00:00.000Z" },
    { "Created at": "2026-03-01T23:00:00.000Z" },
  ]);
  assert.equal(coverage.daysCovered, 1);
});

test("an empty store is unknown coverage, not a zero-day store", () => {
  const snapshot = buildEngineInputSnapshot({ shop: null, orders: [], order_line_items: [] });
  assert.equal(snapshot.rowCount, 0);
  assert.equal(snapshot.coverage.known, false);
  assert.equal(snapshotToCsv(snapshot).trim().split("\n").length, 1, "header only");
});

test("fetched coverage measures one fetch, not the accumulated tables", () => {
  // Same processed_at-first precedence as the normalized projection, so the two
  // numbers are directly comparable.
  const coverage = fetchedOrderCoverage([
    { processed_at: "2026-05-01T00:00:00.000Z", created_at: "2026-09-01T00:00:00.000Z" },
    { processed_at: "2026-05-30T00:00:00.000Z", created_at: "2026-09-01T00:00:00.000Z" },
    { created_at: "2026-05-15T00:00:00.000Z" },
  ]);
  assert.equal(coverage.known, true);
  assert.equal(coverage.earliestOrderAt, "2026-05-01T00:00:00.000Z");
  assert.equal(coverage.daysCovered, 30);
});

test("a fetch of undated orders is unknown coverage", () => {
  assert.equal(fetchedOrderCoverage([{ id: 1 }, { id: 2 }]).known, false);
  assert.equal(fetchedOrderCoverage([]).known, false);
});

// Residual records are no longer detected by date. A record absent from the
// fetch but dated inside the covered period is invisible to any range check, so
// the reconciliation is a membership query against the clean tables — see
// "the published input is the fetched generation, not the union" in
// syncService.integration.test.js.
