"""
tests/test_synthetic_fixtures.py

Structural validation tests for synthetic Shopify fixture CSVs generated by
scripts/generate_synthetic_shopify.py.

These tests verify that the generated fixtures meet the structural constraints
defined in tests/fixtures/synthetic_scenarios.yaml.

Run after generating fixtures:
    python scripts/generate_synthetic_shopify.py
    pytest tests/test_synthetic_fixtures.py -v
"""
from __future__ import annotations

import warnings
from pathlib import Path

import pandas as pd
import pytest
import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
SCENARIOS_YAML = REPO_ROOT / "tests" / "fixtures" / "synthetic_scenarios.yaml"
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures" / "synthetic"

REQUIRED_ORDER_COLUMNS = [
    "Name",
    "Created at",
    "Cancelled at",
    "Lineitem name",
    "Lineitem quantity",
    "Lineitem price",
    "Lineitem discount",
    "Financial Status",
    "Fulfillment Status",
    "Subtotal",
    "Total Discount",
    "Shipping",
    "Taxes",
    "Total",
    "Currency",
    "Customer Email",
    "Billing Name",
    "Shipping Province",
    "Shipping Country",
]

REQUIRED_INVENTORY_COLUMNS = ["SKU", "Product Title", "Available", "Incoming", "Updated At"]


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def scenarios():
    """Load scenario metadata from YAML."""
    with open(SCENARIOS_YAML) as f:
        data = yaml.safe_load(f)
    return data["scenarios"]


def _load_orders(scenario_name: str) -> pd.DataFrame:
    path = FIXTURES_DIR / f"{scenario_name}_orders.csv"
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        df = pd.read_csv(path, low_memory=False)
    return df


def _load_inventory(scenario_name: str) -> pd.DataFrame:
    path = FIXTURES_DIR / f"{scenario_name}_inventory.csv"
    df = pd.read_csv(path, low_memory=False)
    return df


# ---------------------------------------------------------------------------
# Parametrize over all scenarios
# ---------------------------------------------------------------------------

SCENARIO_NAMES = [
    "healthy_beauty_240d",
    "healthy_beauty_low_inventory_240d",
    "supplement_replenishment_240d",
    "small_store_240d",
    "cold_start_45d",
    "promo_anomaly_240d",
]


# ---------------------------------------------------------------------------
# Test: CSV files exist
# ---------------------------------------------------------------------------

class TestFilesExist:
    def test_orders_csv_exists(self, scenarios):
        for name in SCENARIO_NAMES:
            path = FIXTURES_DIR / f"{name}_orders.csv"
            assert path.exists(), f"Missing orders CSV: {path}"

    def test_inventory_csv_exists_where_required(self, scenarios):
        for name in SCENARIO_NAMES:
            cfg = scenarios[name]
            if cfg.get("inventory", False):
                path = FIXTURES_DIR / f"{name}_inventory.csv"
                assert path.exists(), f"Missing inventory CSV: {path}"


# ---------------------------------------------------------------------------
# Test: Required columns present
# ---------------------------------------------------------------------------

class TestRequiredColumns:
    @pytest.mark.parametrize("scenario_name", SCENARIO_NAMES)
    def test_orders_has_required_columns(self, scenario_name, scenarios):
        df = _load_orders(scenario_name)
        for col in REQUIRED_ORDER_COLUMNS:
            assert col in df.columns, (
                f"[{scenario_name}] Missing required column: {col}"
            )

    @pytest.mark.parametrize(
        "scenario_name",
        [n for n in SCENARIO_NAMES if True],
    )
    def test_inventory_has_required_columns(self, scenario_name, scenarios):
        cfg = scenarios[scenario_name]
        if not cfg.get("inventory", False):
            pytest.skip(f"Scenario {scenario_name} has no inventory file")
        df = _load_inventory(scenario_name)
        for col in REQUIRED_INVENTORY_COLUMNS:
            assert col in df.columns, (
                f"[{scenario_name}] Missing inventory column: {col}"
            )


# ---------------------------------------------------------------------------
# Test: Date range within spec
# ---------------------------------------------------------------------------

class TestDateRange:
    @pytest.mark.parametrize("scenario_name", SCENARIO_NAMES)
    def test_date_range_covers_required_window(self, scenario_name, scenarios):
        cfg = scenarios[scenario_name]
        anchor = pd.Timestamp(cfg["anchor_date"])
        days_history = cfg["days_history"]

        df = _load_orders(scenario_name)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            dates = pd.to_datetime(df["Created at"], errors="coerce", utc=True).dt.tz_localize(None)

        actual_earliest = dates.min()
        actual_latest = dates.max()

        assert not pd.isna(actual_earliest), f"[{scenario_name}] No valid dates found"

        # Latest date should not be more than 2 days after anchor
        assert actual_latest <= anchor + pd.Timedelta(days=2), (
            f"[{scenario_name}] Latest date {actual_latest.date()} is after anchor {anchor.date()}"
        )

        # For 240d scenarios: data should go back at least 210 days
        if days_history >= 210:
            cutoff = anchor - pd.Timedelta(days=210)
            assert actual_earliest <= cutoff, (
                f"[{scenario_name}] Earliest date {actual_earliest.date()} > expected cutoff "
                f"anchor-210d = {cutoff.date()}"
            )

    @pytest.mark.parametrize("scenario_name", ["cold_start_45d"])
    def test_cold_start_date_range(self, scenario_name, scenarios):
        """Cold start should have < 60 days of data."""
        cfg = scenarios[scenario_name]
        anchor = pd.Timestamp(cfg["anchor_date"])

        df = _load_orders(scenario_name)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            dates = pd.to_datetime(df["Created at"], errors="coerce", utc=True).dt.tz_localize(None)

        days_span = (dates.max() - dates.min()).days
        assert days_span <= 60, (
            f"[{scenario_name}] Data spans {days_span} days, expected <= 60"
        )


# ---------------------------------------------------------------------------
# Test: Monthly revenue within expected bounds
# ---------------------------------------------------------------------------

class TestMonthlyRevenue:
    @pytest.mark.parametrize(
        "scenario_name",
        [n for n in SCENARIO_NAMES if n not in ("cold_start_45d",)],
    )
    def test_monthly_revenue_in_range(self, scenario_name, scenarios):
        cfg = scenarios[scenario_name]
        rev_min = cfg.get("expected_monthly_revenue_min")
        rev_max = cfg.get("expected_monthly_revenue_max")

        if rev_min is None or rev_max is None:
            pytest.skip(f"No revenue bounds defined for {scenario_name}")

        df = _load_orders(scenario_name)
        paid = df[df["Financial Status"].astype(str).str.lower() == "paid"].copy()
        if paid.empty:
            pytest.skip(f"No paid orders in {scenario_name}")

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            paid["_date"] = pd.to_datetime(paid["Created at"], errors="coerce", utc=True).dt.tz_localize(None)
            paid_dedup = paid.drop_duplicates("Name")
            paid_dedup = paid_dedup.copy()
            paid_dedup["_month"] = paid_dedup["_date"].dt.to_period("M")
            monthly = paid_dedup.groupby("_month")["Subtotal"].sum()

        # Only check middle months (skip first and last partial months)
        if len(monthly) > 2:
            mid_months = monthly.iloc[1:-1]
            out_of_range = []
            for m, rev in mid_months.items():
                # Promo anomaly has an intentional spike; apply wide tolerance
                if scenario_name == "promo_anomaly_240d":
                    if rev < rev_min * 0.3 or rev > rev_max * 4.0:
                        out_of_range.append((str(m), rev))
                else:
                    if rev < rev_min * 0.4 or rev > rev_max * 2.0:
                        out_of_range.append((str(m), rev))

            assert not out_of_range, (
                f"[{scenario_name}] Months with revenue out of range: {out_of_range}"
            )


# ---------------------------------------------------------------------------
# Test: Customer email coverage
# ---------------------------------------------------------------------------

class TestCustomerEmailCoverage:
    @pytest.mark.parametrize(
        "scenario_name",
        ["healthy_beauty_240d", "healthy_beauty_low_inventory_240d",
         "supplement_replenishment_240d", "promo_anomaly_240d"],
    )
    def test_email_coverage_gte_70pct(self, scenario_name, scenarios):
        df = _load_orders(scenario_name)
        has_email = df["Customer Email"].notna() & (df["Customer Email"].astype(str).str.strip() != "")
        coverage = has_email.mean()
        assert coverage >= 0.70, (
            f"[{scenario_name}] Customer email coverage {coverage:.1%} < 70% threshold"
        )

    @pytest.mark.parametrize(
        "scenario_name",
        ["healthy_beauty_240d", "healthy_beauty_low_inventory_240d", "supplement_replenishment_240d"],
    )
    def test_has_repeat_customers(self, scenario_name, scenarios):
        """Verify at least some customers have placed 2+ orders."""
        df = _load_orders(scenario_name)
        paid = df[df["Financial Status"].astype(str).str.lower() == "paid"]
        paid_dedup = paid.drop_duplicates("Name")
        cust_orders = paid_dedup.groupby("Customer Email").size()
        repeat_customers = (cust_orders >= 2).sum()
        assert repeat_customers >= 10, (
            f"[{scenario_name}] Too few repeat customers: {repeat_customers} (expected >= 10)"
        )


# ---------------------------------------------------------------------------
# Test: Inventory SKU completeness
# ---------------------------------------------------------------------------

class TestInventoryCompleteness:
    @pytest.mark.parametrize(
        "scenario_name",
        [n for n in SCENARIO_NAMES if True],
    )
    def test_inventory_has_multiple_skus(self, scenario_name, scenarios):
        cfg = scenarios[scenario_name]
        if not cfg.get("inventory", False):
            pytest.skip(f"No inventory for {scenario_name}")

        inv = _load_inventory(scenario_name)
        assert len(inv) >= 5, (
            f"[{scenario_name}] Inventory has only {len(inv)} SKUs, expected >= 5"
        )

    def test_low_inventory_hero_sku(self, scenarios):
        """Verify the hero SKU (first product) has low inventory in the low-inventory scenario."""
        inv = _load_inventory("healthy_beauty_low_inventory_240d")
        hero_available = inv.iloc[0]["Available"]
        assert hero_available <= 10, (
            f"Hero SKU available={hero_available} should be <= 10 for low-inventory scenario"
        )

    def test_normal_inventory_not_low(self, scenarios):
        """Verify the healthy scenario has adequate stock for all SKUs."""
        inv = _load_inventory("healthy_beauty_240d")
        low_stock = inv[inv["Available"] <= 10]
        assert len(low_stock) == 0, (
            f"healthy_beauty_240d should have no low-stock SKUs; found: {low_stock[['SKU', 'Available']].to_dict('records')}"
        )


# ---------------------------------------------------------------------------
# Test: Order structure sanity
# ---------------------------------------------------------------------------

class TestOrderSanity:
    @pytest.mark.parametrize("scenario_name", SCENARIO_NAMES)
    def test_order_names_are_sequential(self, scenario_name, scenarios):
        df = _load_orders(scenario_name)
        order_names = df["Name"].unique()
        assert len(order_names) >= 10, (
            f"[{scenario_name}] Too few unique orders: {len(order_names)}"
        )
        # All names should start with '#'
        starts_with_hash = all(str(n).startswith("#") for n in order_names)
        assert starts_with_hash, (
            f"[{scenario_name}] Some order names don't start with '#'"
        )

    @pytest.mark.parametrize("scenario_name", SCENARIO_NAMES)
    def test_financial_status_values(self, scenario_name, scenarios):
        df = _load_orders(scenario_name)
        valid = {"paid", "refunded", "partially_refunded"}
        actual = set(df["Financial Status"].astype(str).str.lower().unique())
        invalid = actual - valid
        assert not invalid, (
            f"[{scenario_name}] Invalid Financial Status values: {invalid}"
        )

    @pytest.mark.parametrize("scenario_name", SCENARIO_NAMES)
    def test_currency_is_usd(self, scenario_name, scenarios):
        df = _load_orders(scenario_name)
        assert (df["Currency"] == "USD").all(), (
            f"[{scenario_name}] Non-USD currency found"
        )

    @pytest.mark.parametrize("scenario_name", SCENARIO_NAMES)
    def test_shipping_country_is_us(self, scenario_name, scenarios):
        df = _load_orders(scenario_name)
        assert (df["Shipping Country"] == "US").all(), (
            f"[{scenario_name}] Non-US country found"
        )

    @pytest.mark.parametrize("scenario_name", SCENARIO_NAMES)
    def test_subtotal_positive(self, scenario_name, scenarios):
        df = _load_orders(scenario_name)
        paid = df[df["Financial Status"].astype(str).str.lower() == "paid"]
        paid_dedup = paid.drop_duplicates("Name")
        subtotals = pd.to_numeric(paid_dedup["Subtotal"], errors="coerce")
        assert (subtotals > 0).all(), (
            f"[{scenario_name}] Some paid orders have non-positive Subtotal"
        )


# ---------------------------------------------------------------------------
# Test: Promo anomaly has spike
# ---------------------------------------------------------------------------

class TestPromoAnomaly:
    def test_promo_month_has_higher_revenue(self, scenarios):
        cfg = scenarios["promo_anomaly_240d"]
        promo_month_idx = cfg.get("promo_month_index", 4)

        df = _load_orders("promo_anomaly_240d")
        paid = df[df["Financial Status"].astype(str).str.lower() == "paid"].copy()
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            paid["_date"] = pd.to_datetime(paid["Created at"], errors="coerce", utc=True).dt.tz_localize(None)
            paid_dedup = paid.drop_duplicates("Name")
            paid_dedup = paid_dedup.copy()
            paid_dedup["_month"] = paid_dedup["_date"].dt.to_period("M")
            monthly = paid_dedup.groupby("_month")["Subtotal"].sum()

        if len(monthly) <= promo_month_idx:
            pytest.skip("Not enough months to check promo spike")

        monthly_list = list(monthly)
        promo_rev = monthly_list[promo_month_idx]
        baseline_months = [r for i, r in enumerate(monthly_list) if i != promo_month_idx and r > 0]
        baseline_avg = sum(baseline_months) / len(baseline_months) if baseline_months else 1

        assert promo_rev >= baseline_avg * 1.5, (
            f"Promo month revenue ${promo_rev:,.0f} should be >= 1.5x baseline ${baseline_avg:,.0f}"
        )

    def test_promo_month_has_high_discounts(self, scenarios):
        cfg = scenarios["promo_anomaly_240d"]
        promo_month_idx = cfg.get("promo_month_index", 4)
        expected_discount_pct = cfg.get("promo_discount_pct", 0.35)

        df = _load_orders("promo_anomaly_240d")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            df["_date"] = pd.to_datetime(df["Created at"], errors="coerce", utc=True).dt.tz_localize(None)
            df["_month"] = df["_date"].dt.to_period("M")

        months = sorted(df["_month"].dropna().unique())
        if len(months) <= promo_month_idx:
            pytest.skip("Not enough months")

        promo_month = months[promo_month_idx]
        promo_data = df[df["_month"] == promo_month].copy()
        promo_data["_discount"] = pd.to_numeric(promo_data["Total Discount"], errors="coerce")
        promo_data["_subtotal"] = pd.to_numeric(promo_data["Subtotal"], errors="coerce")
        promo_dedup = promo_data.drop_duplicates("Name")
        promo_dedup = promo_dedup[promo_dedup["_subtotal"] > 0]
        if promo_dedup.empty:
            pytest.skip("No paid promo month orders")

        avg_discount_pct = (promo_dedup["_discount"] / promo_dedup["_subtotal"]).mean()
        assert avg_discount_pct >= 0.15, (
            f"Promo month average discount {avg_discount_pct:.1%} should be >= 15%"
        )


# ---------------------------------------------------------------------------
# Test: Cold start has short history
# ---------------------------------------------------------------------------

class TestColdStart:
    def test_cold_start_has_short_history(self, scenarios):
        cfg = scenarios["cold_start_45d"]
        expected_days = cfg["days_history"]

        df = _load_orders("cold_start_45d")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            dates = pd.to_datetime(df["Created at"], errors="coerce", utc=True).dt.tz_localize(None)

        span = (dates.max() - dates.min()).days
        # Allow up to 5 days of slack
        assert span <= expected_days + 5, (
            f"cold_start_45d spans {span} days, expected <= {expected_days + 5}"
        )

    def test_cold_start_is_shorter_than_healthy(self, scenarios):
        cold = _load_orders("cold_start_45d")
        healthy = _load_orders("healthy_beauty_240d")

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            cold_dates = pd.to_datetime(cold["Created at"], errors="coerce", utc=True).dt.tz_localize(None)
            healthy_dates = pd.to_datetime(healthy["Created at"], errors="coerce", utc=True).dt.tz_localize(None)

        cold_span = (cold_dates.max() - cold_dates.min()).days
        healthy_span = (healthy_dates.max() - healthy_dates.min()).days

        assert cold_span < healthy_span, (
            f"cold_start span ({cold_span}d) should be less than healthy_beauty span ({healthy_span}d)"
        )


# ---------------------------------------------------------------------------
# Test: Supplement has reliable reorder pattern
# ---------------------------------------------------------------------------

class TestSupplementReplenishment:
    def test_supplement_customers_have_multiple_orders(self, scenarios):
        df = _load_orders("supplement_replenishment_240d")
        paid = df[df["Financial Status"].astype(str).str.lower() == "paid"]
        paid_dedup = paid.drop_duplicates("Name")
        cust_orders = paid_dedup.groupby("Customer Email").size()
        multi_order = (cust_orders >= 2).sum()
        # Supplement customers should have very high repeat rate
        repeat_rate = multi_order / max(len(cust_orders), 1)
        assert repeat_rate >= 0.50, (
            f"supplement_replenishment should have >= 50% repeat rate, got {repeat_rate:.1%}"
        )


# ---------------------------------------------------------------------------
# Test: Small store has lower order volume
# ---------------------------------------------------------------------------

class TestSmallStore:
    def test_small_store_lower_monthly_orders(self, scenarios):
        small = _load_orders("small_store_240d")
        healthy = _load_orders("healthy_beauty_240d")

        small_orders = small["Name"].nunique()
        healthy_orders = healthy["Name"].nunique()

        assert small_orders < healthy_orders, (
            f"small_store ({small_orders} orders) should have fewer than healthy_beauty ({healthy_orders} orders)"
        )
