export const baseEngineRun = {
  store_id: "testing-dev-utkexvrj.myshopify.com",
  run_timestamp: "2026-06-01T08:22:11Z",
  run_month: 2,
  slate: {
    recommended_now: [
      {
        play_id: "winback_dormant_cohort",
        play_name: "Dormant buyer winback",
        role: "recommended_now",
        audience_archetype: "DORMANT_BUYER",
        mechanism: "Re-engage customers with purchase history who have gone quiet, using a personalized restock or discovery offer.",
        audience_size: 214,
        evidence: { evidence_class: "directional", p_value: null, effect: null },
        revenue_range: { low: 4200, high: 11800, currency: "USD" },
        gate_status: { cohort_pvalue: false, prior_validation: true, ml_fit: false },
        model: "placeholder_bg_nbd",
      },
      {
        play_id: "cohort_journey_first_to_second",
        play_name: "First-to-second purchase journey",
        role: "recommended_now",
        audience_archetype: "FIRST_TIME_BUYER",
        mechanism: "Trigger post-purchase education and complementary SKU suggestions within 72 hours of delivery.",
        audience_size: 89,
        evidence: { evidence_class: "prior-anchored", p_value: null, effect: null },
        revenue_range: { low: 1800, high: 5200, currency: "USD" },
        gate_status: { cohort_pvalue: false, prior_validation: true, ml_fit: false },
        model: "placeholder_cf_affinity",
      },
    ],
    recommended_experiment: [
      {
        play_id: "aov_lift_threshold_bundle",
        play_name: "AOV threshold bundle test",
        role: "recommended_experiment",
        audience_archetype: "THRESHOLD_NEAR_BUYER",
        mechanism: "Test a dynamic add-more-to-unlock nudge for customers close to the free shipping threshold.",
        audience_size: 134,
        evidence: { evidence_class: "prior-anchored", p_value: null, effect: null },
        revenue_range: { low: 2200, high: 7600, currency: "USD" },
        gate_status: { cohort_pvalue: false, prior_validation: true, ml_fit: false },
        model: "placeholder_gamma_gamma",
      },
    ],
    considered: [
      {
        play_id: "replenishment_due",
        play_name: "Replenishment due",
        reason_code: "REAL_ENGINE_NOT_CONNECTED",
        mechanism: "Hold until SKU-level cadence and survival model outputs are available.",
        audience_size: 0,
      },
      {
        play_id: "discount_dependency_hygiene",
        play_name: "Discount dependency hygiene",
        reason_code: "NEEDS_VALIDATION",
        mechanism: "Hold until discount elasticity can be estimated from historical promo behavior.",
        audience_size: 0,
      },
    ],
  },
  predictive_models: {
    bg_nbd: {
      display_name: "BG/NBD purchase probability",
      name: "placeholder_bg_nbd",
      fit_status: "PLACEHOLDER",
      n_observed: 0,
      training_window_days: 365,
      holdout_mape: null,
      fit_warnings: ["Real engine model not connected yet"],
    },
    gamma_gamma: {
      display_name: "Gamma-Gamma monetary value",
      name: "placeholder_gamma_gamma",
      fit_status: "PLACEHOLDER",
      n_observed: 0,
      training_window_days: 365,
      holdout_mape: null,
      fit_warnings: ["Waiting for Atul engine output"],
    },
    cohort_retention: {
      display_name: "Cohort retention curves",
      name: "placeholder_cohort_retention",
      fit_status: "PLACEHOLDER",
      n_observed: 0,
      training_window_days: 365,
      holdout_mape: null,
      fit_warnings: [],
    },
  },
  audience_segments: [
    { label: "Known customers", n: 0, pct: 0, color_role: "loyal" },
    { label: "Purchased orders", n: 0, pct: 0, color_role: "champion" },
    { label: "Catalog products", n: 0, pct: 0, color_role: "new" },
    { label: "Dormant candidates", n: 0, pct: 0, color_role: "dormant" },
  ],
  cohort_retention: {
    curves: [
      { cohort_label: "Month 0", points: [{ month: 0, p50: 1 }, { month: 1, p50: 0.36 }, { month: 2, p50: 0.24 }, { month: 3, p50: 0.18 }] },
      { cohort_label: "Month 1", points: [{ month: 0, p50: 1 }, { month: 1, p50: 0.39 }, { month: 2, p50: 0.28 }] },
      { cohort_label: "Month 2", points: [{ month: 0, p50: 1 }, { month: 1, p50: 0.42 }] },
    ],
  },
  month_2_delta: {
    ltv_evolution: { prev_p50: 0, curr_p50: 0, delta_pct: 0 },
    new_cohorts_entering: 1,
    audiences_grew: ["FIRST_TIME_BUYER"],
    audiences_shrank: ["DORMANT_BUYER"],
    model_refit_divergence: [{ model: "bg_nbd", prev: "PLACEHOLDER", curr: "PLACEHOLDER" }],
  },
};

export const mockCampaignPackages = [
  {
    id: "winback",
    playTitle: "Dormant buyer winback",
    status: "ready",
    builtAt: "Jun 1",
    customers: 214,
    segment: "Dormant buyers with prior purchase history",
    subject: "Ready for your next order?",
    previewText: "A personalized restock nudge for returning customers.",
    bodyH2: "We saved a spot for your next favorite.",
    bodyP1: "Your last order gives us a useful clue about what to show next.",
    bodyP2: "This campaign will be replaced by the real engine copy once Atul's output is connected.",
    cta: "Shop now",
    sendTime: "Manual review",
    suppression: "Recent purchasers, unsubscribes, suppressed profiles",
  },
  {
    id: "first-to-second",
    playTitle: "First-to-second purchase journey",
    status: "building",
    builtAt: "Jun 1",
    customers: 89,
    segment: "First-time buyers",
    subject: "Your next step with us",
    previewText: "Education and cross-sell journey.",
    bodyH2: "Make the most of your first order.",
    bodyP1: "A guided follow-up can help customers find the next product.",
    bodyP2: "This is a placeholder package until the engine returns final content.",
    cta: "Explore picks",
    sendTime: "Manual review",
    suppression: "Recent purchasers, unsubscribes",
  },
];
