"""Internal-only receipts/debug.html renderer — Milestone 9, T9.5.

This is a merchant-INVISIBLE debug page. It is NOT linked from
``briefing.html`` and MUST NOT change any merchant-facing renderer
behavior. Its only job is to surface the internal evidence diagnostics
(``evidence_class``, ``p_internal``, ``ci_internal``, ``observed_effect``,
``n``, ``revenue_range.drivers``, suppression reasons) so an internal
reviewer can audit a run without grepping ``engine_run.json`` by hand.

Per ``agent_outputs/implementation-manager-overhaul-plan-final.md`` M9 T9.5:

    A merchant-invisible debug HTML reads engine_run.json and shows
    p_internal/ci_internal/drivers for each play. Lives at receipts/debug.html.

Hard contract (rules this module enforces by construction):

- The output HTML is clearly labeled as INTERNAL and bears a no-distribute
  banner. The merchant briefing renderer does NOT load this page.
- The output may show ``p_internal`` and ``ci_internal``. These strings
  are explicitly forbidden in ``briefing.html`` by the M8 invariant; the
  debug page is the *only* allowed surface for them.
- The output is deterministic (no randomness, no timestamps that vary
  across runs of the same EngineRun input — except when the EngineRun
  itself carries a timestamp).
- The renderer is a pure function: ``render_debug_html(engine_run) -> str``.
  No I/O. The caller writes the file. This matches the V2 renderer's
  contract.
- The renderer never raises on missing fields. Empty PlayCards / missing
  measurements / suppressed ranges all render an explanatory cell rather
  than crashing.
"""

from __future__ import annotations

import html
from typing import Any, Iterable, List, Optional

from .engine_run import (
    Audience,
    DataQualityFlag,
    EngineRun,
    EvidenceClass,
    Measurement,
    PlayCard,
    RejectedPlay,
    RevenueRange,
)


# Sentinel banner displayed at the top of every debug page. Search-tooled.
INTERNAL_BANNER = (
    "INTERNAL DIAGNOSTICS — NOT FOR MERCHANT DISTRIBUTION. "
    "Generated by BeaconAI engine for internal review only."
)


def _esc(value: Any) -> str:
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


def _fmt_float(value: Any, ndigits: int = 6) -> str:
    if value is None:
        return "—"
    try:
        f = float(value)
    except (TypeError, ValueError):
        return _esc(value)
    if f != f:  # NaN
        return "NaN"
    return f"{f:.{ndigits}f}"


def _fmt_int(value: Any) -> str:
    if value is None:
        return "—"
    try:
        return f"{int(value):,}"
    except (TypeError, ValueError):
        return _esc(value)


def _fmt_money(value: Any) -> str:
    if value is None:
        return "—"
    try:
        return f"${float(value):,.0f}"
    except (TypeError, ValueError):
        return _esc(value)


def _fmt_ci(ci: Any) -> str:
    if not ci:
        return "—"
    try:
        lo, hi = ci[0], ci[1]
    except (TypeError, ValueError, IndexError):
        return _esc(ci)
    return f"[{_fmt_float(lo)}, {_fmt_float(hi)}]"


def _fmt_drivers(drivers: Iterable[dict]) -> str:
    rows: List[str] = []
    for d in drivers or []:
        if not isinstance(d, dict):
            continue
        name = _esc(d.get("name", ""))
        source = _esc(d.get("source", ""))
        # Build a "value (extras)" string preserving provenance fields.
        extras = ", ".join(
            f"{_esc(k)}={_esc(v)}"
            for k, v in d.items()
            if k not in {"name", "source", "value"}
        )
        value = d.get("value")
        if value is not None:
            row = f"<li><code>{name}</code> = <code>{_esc(value)}</code> "
        else:
            row = f"<li><code>{name}</code> "
        row += f"<span class='dbg-tag'>source={source}</span>"
        if extras:
            row += f" <span class='dbg-extras'>{extras}</span>"
        row += "</li>"
        rows.append(row)
    if not rows:
        return "<em>(no drivers)</em>"
    return "<ul class='dbg-drivers'>" + "".join(rows) + "</ul>"


def _render_audience(aud: Optional[Audience]) -> str:
    if aud is None:
        return "<td class='dbg-none'>—</td>"
    parts: List[str] = []
    if aud.id:
        parts.append(f"id=<code>{_esc(aud.id)}</code>")
    if aud.size is not None:
        parts.append(f"size={_fmt_int(aud.size)}")
    if aud.fraction_of_base is not None:
        try:
            parts.append(f"frac={float(aud.fraction_of_base):.3f}")
        except (TypeError, ValueError):
            pass
    return "<td>" + (", ".join(parts) or "—") + "</td>"


def _render_measurement_cell(m: Optional[Measurement]) -> str:
    if m is None:
        return "<td class='dbg-none'>(targeting — no measurement by contract)</td>"
    rows = [
        f"<div>metric: <code>{_esc(m.metric)}</code></div>",
        f"<div>observed_effect: <code>{_fmt_float(m.observed_effect)}</code></div>",
        f"<div>n: <code>{_fmt_int(m.n)}</code></div>",
        f"<div>primary_window: <code>{_esc(m.primary_window)}</code></div>",
        f"<div>consistency_across_windows: <code>{_esc(m.consistency_across_windows)}</code></div>",
        f"<div><strong>p_internal</strong>: <code>{_fmt_float(m.p_internal)}</code></div>",
        f"<div><strong>ci_internal</strong>: <code>{_fmt_ci(m.ci_internal)}</code></div>",
    ]
    return "<td class='dbg-measurement'>" + "".join(rows) + "</td>"


def _render_revenue_range_cell(rr: Optional[RevenueRange]) -> str:
    if rr is None:
        return "<td class='dbg-none'>—</td>"
    if rr.suppressed:
        # Find the suppression reason driver (name='suppression_reason') if present.
        reason = "(suppressed; no merchant-facing $)"
        for d in rr.drivers or []:
            if isinstance(d, dict) and d.get("name") == "suppression_reason":
                reason = f"suppressed: {d.get('reason') or d.get('value') or 'unknown'}"
                break
        body = f"<div class='dbg-suppressed'>{_esc(reason)}</div>"
        body += "<details><summary>drivers</summary>" + _fmt_drivers(rr.drivers) + "</details>"
        return "<td>" + body + "</td>"
    src = rr.source.value if (rr.source is not None and hasattr(rr.source, "value")) else _esc(rr.source)
    body = (
        f"<div>p10={_fmt_money(rr.p10)} p50={_fmt_money(rr.p50)} p90={_fmt_money(rr.p90)}</div>"
        f"<div>source: <code>{_esc(src)}</code></div>"
        f"<details><summary>drivers</summary>" + _fmt_drivers(rr.drivers) + "</details>"
    )
    return "<td>" + body + "</td>"


def _render_play_row(card: PlayCard) -> str:
    ec = card.evidence_class.value if hasattr(card.evidence_class, "value") else _esc(card.evidence_class)
    confidence = _esc(card.confidence_label or "")
    return (
        "<tr>"
        f"<td><code>{_esc(card.play_id)}</code></td>"
        f"<td><span class='dbg-evidence dbg-evidence--{_esc(ec)}'>{_esc(ec)}</span></td>"
        f"<td>{confidence or '—'}</td>"
        + _render_audience(card.audience)
        + _render_measurement_cell(card.measurement)
        + _render_revenue_range_cell(card.revenue_range)
        + "</tr>"
    )


def _render_rejected_row(rp: RejectedPlay) -> str:
    # S13.6-T1a (Option D): ``reason_text`` / ``evidence_snapshot`` /
    # ``would_fire_if`` stripped per Pivot 2. The debug table renders
    # only the typed ``reason_code`` enum value; downstream narration
    # owns the detail / snapshot / would-fire-if composition.
    rc = rp.reason_code.value if hasattr(rp.reason_code, "value") else _esc(rp.reason_code)
    return (
        "<tr>"
        f"<td><code>{_esc(rp.play_id)}</code></td>"
        f"<td><span class='dbg-reason'>{_esc(rc)}</span></td>"
        "</tr>"
    )


def _render_data_quality_flags(flags: Iterable[DataQualityFlag]) -> str:
    items = [
        f.value if hasattr(f, "value") else str(f)
        for f in (flags or [])
    ]
    if not items:
        return "<em>(none)</em>"
    return "<ul>" + "".join(f"<li><code>{_esc(i)}</code></li>" for i in items) + "</ul>"


_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       margin: 24px; color: #222; max-width: 1100px; }
h1 { margin-bottom: 4px; }
.dbg-banner { background: #ffefc4; border: 1px solid #b58900;
              padding: 10px 14px; border-radius: 4px; margin: 12px 0 24px;
              font-weight: 600; }
table { border-collapse: collapse; width: 100%; margin: 12px 0 24px;
        font-size: 13px; }
th, td { border: 1px solid #ddd; padding: 6px 8px; vertical-align: top; text-align: left; }
th { background: #f4f4f4; }
code { background: #f6f6f6; padding: 1px 4px; border-radius: 3px; font-size: 12px; }
.dbg-evidence { padding: 1px 6px; border-radius: 3px; font-size: 11px;
                text-transform: uppercase; }
.dbg-evidence--measured { background: #d4edda; color: #155724; }
.dbg-evidence--directional { background: #d1ecf1; color: #0c5460; }
.dbg-evidence--targeting { background: #fff3cd; color: #856404; }
.dbg-evidence--weak { background: #f8d7da; color: #721c24; }
.dbg-reason { font-family: monospace; font-size: 11px; color: #6c757d; }
.dbg-tag, .dbg-extras { font-size: 11px; color: #6c757d; }
.dbg-suppressed { color: #6c757d; font-style: italic; }
.dbg-none { color: #aaa; }
section { margin: 24px 0; }
"""


def render_debug_html(engine_run: EngineRun) -> str:
    """Return the full HTML string for ``receipts/debug.html``.

    Pure function. No I/O. The caller writes the file.
    """
    abstain = engine_run.abstain
    abstain_state = abstain.state.value if (abstain is not None and abstain.state is not None) else "?"
    # S13.6-T1a (Option D): ``Abstain.reason`` stripped per Pivot 2.
    abstain_reason = None
    scale = engine_run.scale
    scale_lines: List[str] = []
    if scale is not None:
        if scale.monthly_revenue is not None:
            scale_lines.append(f"monthly_revenue={_fmt_money(scale.monthly_revenue)}")
        if scale.customer_base_est is not None:
            scale_lines.append(f"customer_base_est={_fmt_int(scale.customer_base_est)}")
        if scale.materiality_floor is not None:
            scale_lines.append(f"materiality_floor={_fmt_money(scale.materiality_floor)}")
    scale_block = ", ".join(scale_lines) or "—"

    # ---- Header / state-of-store --------------------------------------------
    head = f"""<!doctype html>
<html lang='en'>
<head>
<meta charset='utf-8'>
<title>BeaconAI internal debug — {_esc(engine_run.store_id or 'unknown')}</title>
<style>{_CSS}</style>
</head>
<body>
<h1>BeaconAI internal diagnostics</h1>
<div class='dbg-banner'>{_esc(INTERNAL_BANNER)}</div>
<section>
<h2>Run identity</h2>
<table>
<tr><th>store_id</th><td><code>{_esc(engine_run.store_id)}</code></td></tr>
<tr><th>run_id</th><td><code>{_esc(engine_run.run_id)}</code></td></tr>
<tr><th>anchor_date</th><td><code>{_esc(engine_run.anchor_date)}</code></td></tr>
<tr><th>schema_version</th><td><code>{_esc(engine_run.schema_version)}</code></td></tr>
<tr><th>cold_start</th><td><code>{_esc(engine_run.cold_start)}</code></td></tr>
<tr><th>decision_state</th><td><code>{_esc(abstain_state)}</code></td></tr>
<tr><th>abstain_reason</th><td>{_esc(abstain_reason or '')}</td></tr>
<tr><th>scale</th><td>{_esc(scale_block)}</td></tr>
<tr><th>data_quality_flags</th><td>{_render_data_quality_flags(engine_run.data_quality_flags)}</td></tr>
</table>
</section>
"""

    # ---- Recommended ---------------------------------------------------------
    rec_rows = "".join(_render_play_row(c) for c in (engine_run.recommendations or []))
    if not rec_rows:
        rec_rows = "<tr><td colspan='6'><em>(no recommendations on this run)</em></td></tr>"
    recommended = f"""<section>
<h2>Recommended ({len(engine_run.recommendations or [])})</h2>
<table>
<thead><tr>
<th>play_id</th>
<th>evidence_class</th>
<th>confidence_label</th>
<th>audience</th>
<th>measurement (p_internal / ci_internal)</th>
<th>revenue_range (drivers)</th>
</tr></thead>
<tbody>{rec_rows}</tbody>
</table>
</section>
"""

    # ---- Considered / rejected ----------------------------------------------
    rej_rows = "".join(_render_rejected_row(r) for r in (engine_run.considered or []))
    if not rej_rows:
        rej_rows = "<tr><td colspan='2'><em>(no considered/rejected entries on this run)</em></td></tr>"
    considered = f"""<section>
<h2>Considered, not recommended ({len(engine_run.considered or [])})</h2>
<table>
<thead><tr>
<th>play_id</th>
<th>reason_code</th>
</tr></thead>
<tbody>{rej_rows}</tbody>
</table>
</section>
"""

    # ---- Watching ------------------------------------------------------------
    watching_rows: List[str] = []
    for w in engine_run.watching or []:
        watching_rows.append(
            "<tr>"
            f"<td><code>{_esc(w.metric)}</code></td>"
            f"<td>{_esc(w.current)}</td>"
            f"<td>{_esc(w.prior)}</td>"
            f"<td>{_esc(w.trend)}</td>"
            f"<td>{_esc(w.threshold_to_act or '')}</td>"
            "</tr>"
        )
    if not watching_rows:
        watching_rows.append("<tr><td colspan='5'><em>(none)</em></td></tr>")
    watching = f"""<section>
<h2>Watching ({len(engine_run.watching or [])})</h2>
<table>
<thead><tr><th>metric</th><th>current</th><th>prior</th><th>trend</th><th>threshold_to_act</th></tr></thead>
<tbody>{''.join(watching_rows)}</tbody>
</table>
</section>
"""

    foot = "</body></html>"
    return head + recommended + considered + watching + foot


__all__ = ["INTERNAL_BANNER", "render_debug_html"]
